### ISSUE TITLE
[Question]: How do I filters the records being shown in the switcher

### ISSUE THREAD

**Issue by loveshpatni** [howdu/filament-record-switcher#7]
### What happened?

I have some Test records in my application database. Can't seem to find an easy way to exclude them

### How to reproduce the bug

I have some test records in my db and some actual records. When I use the record switcher there is no easy way to exclude the test records. Is there a way to exclude these?

### Package Version

1.0.3

### PHP Version

8.2.0

### Laravel Version

11.36

### Which operating systems does with happen with?

Linux

**Comment by loveshpatni** [comment]
Instead of querying the model for all the records, could you use the query from the Filament Resource?

**Comment by howdu** [comment]
Inside your resource page you add a `modifyRecordSwitcherQuery` method to add any custom logic.  

The main method to fetch the records is:
<img width="761" alt="Screenshot 2024-12-22 at 13 40 01" src="https://github.com/user-attachments/assets/69244644-ada7-480a-841f-8823fade6531" />

**Comment by loveshpatni** [comment]
Thank you. This worked
